### PR TITLE
[WIP] Add Parquet Format

### PR DESCRIPTION
**Pull request by eakmanrq**
Still being actively developed. Currently passing some basic tests.

### CODE REVIEW

**Comment by vigneshsenapathy** [comment]
@eakmanrq : any idea when this will be merged in?

**Comment by vigneshsenapathy** [comment]
@eakmanrq : i checked you code by running it locally i am getting the following error:

{"exception":{"message":"org.apache.parquet.column.ParquetProperties.getAllocator()Lorg\/apache\/parquet\/bytes\/ByteBufferAllocator;","class":"java.lang.NoSuchMethodError","stacktrace":"java.lang.NoSuchMethodError: org.apache.parquet.column.ParquetProperties.getAllocator()Lorg\/apache\/parquet\/bytes\/ByteBufferAllocator;\n\tat org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:105)\n\tat org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:97)\n\tat org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:290)\n\tat org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:530)\n\tat io.confluent.connect.s3.format.parquet.ParquetRecordWriterProvider$1.write(ParquetRecordWriterProvider.java:82)\n\tat io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:477)\n\tat io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:267)\n\tat io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:212)\n\tat io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:176)\n\tat io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:195)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)"},"level":"ERROR","location":{"class":"org.apache.kafka.connect.runtime.WorkerSinkTask","file":"WorkerSinkTask.java","method":"deliverMessages","line":"584"},"logger":"org.apache.kafka.connect.runtime.WorkerSinkTask","message":"WorkerSinkTask{id=vignesh-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted.","host":"391c89bc3b19","tags":["vignesh-sink"],"@timestamp":"2018-08-09T15:14:45.177Z","thread":"pool-16-thread-1","@version":"1"}

**Comment by eakmanrq** [comment]
@vigneshsenapathy Sadly my priorities changed and I no longer have time to work on this. This was working for simple tests but I wasn't able to do full tests so it is not surprising that you ran into an issue. If I personally get time or my professional priorities change then I will be happy to continue moving this forward.

**Comment by kujon** [comment]
@confluentinc would you be interested in someone else picking up this development?

**Comment by tony810430** [comment]
Hi @eakmanrq, I have sent a PR to your branch to make it rebase to master, and also fix some minor issues. I didn't add more test on it. Just make it work on my machine.

Besides, this PR implemented an interface `PositionOutputStream` from parquet library. If someone who want to build it, you should upgrade your parquet version to at least `1.10.0`. If who want to use it,  make sure your parquet dependencies in kafka connect is upgraded as well.

**Comment by jocelyndrean** [comment]
@tony810430 Amazing job!🚀 Maybe you should submit your own PR on this repo, because unfortunately @eakmanrq doesn't work on this PR anymore due to a lack of time and I don't know if he will be able to merge your PR.

**Comment by eakmanrq** [comment]
Great job @tony810430! Excited to see someone else jump on this and contribute! 💯 I have merged the PR.

**Comment by tony810430** [comment]
@eakmanrq, It seems that I missed to eliminate those unnecessary whitespaces and blank lines.
I have sent one more PR to deal with it. Please help to review it. Thx.

@jocelyndrean, Since what I do is just rebase to master and make the test pass, I didn't focus on reviewing the details. I prefer to leave it as one PR only, because I don't have confidence to take over it for now. Next, I will try to use it and read the code, and maybe I will be able to continue @eakmanrq 's work after having a full understanding of this PR.

**Comment by kkonstantine** [comment]
@tony810430 @eakmanrq it's really nice to see progress on this highly desirable feature. 
Please remove `[WIP]` when you believe this is ready for reviews.

**Comment by kkonstantine** [comment]
Most of the work described here was imported and merged as part of https://github.com/confluentinc/kafka-connect-storage-cloud/pull/241

Closing this PR without merging. Thanks for the initial work @eakmanrq !

**Pull request closed without merging**
