### PR TITLE
HCD 329:Integration tests for network interruptions and Permission change

### PR DESCRIPTION
**Pull request by SanchayGupta1197**
Link to JIRA ticket -
[https://confluentinc.atlassian.net/browse/HCD-329](https://confluentinc.atlassian.net/browse/HCD-329)

Added integration test using **EmbeddedConnectCluster**, **Squid Proxy Test Container** and [Pumba](https://github.com/alexei-led/pumba) for the following scenarios -

**S3 Sink Connector**

- **testToAssertConnectorAndDestinationRecords():** End to End IT test (success scenario)
- **testWithRevokedWritePermissions():** IT test for changes to user's write permissions 
- **testWithNetworkUnavailability():** IT test for Database server unavailability by shutting down Squid Proxy Container
- **testWithNetworkInterruption():** IT test for network delays/interruptions using Pumba and SquidProxy Container
       

**Updated deprecated code:**
- org.junit.Assert.assertThat -> org.hamcrest.MatcherAssert.assertThat (mentioned in org.junit.Assert.assertThat documentation)
- s3.doesBucketExist -> s3.doesBucketExistV2 (newer one raise a Exception if credentials are invalid, instead of returning true)
- org.junit.Rule and ExpectedException.none() -> `@test(expected= Exception.class)`

### CODE REVIEW

**Comment by SanchayGupta1197** [comment]
Currently skipped IT test cases to pass Jenkins build, These can be skipped using the `maven-failsafe-plugin` but wasn't able to locate the plugin neither in the **parent pom.xml** nor in the **kafka-connect-s3 pom.xml**

**Comment by dosvath** [comment]
Thanks @SanchayGupta1197, @levzem we may want to get the other PR in before? https://github.com/confluentinc/kafka-connect-storage-cloud/pull/351

**Comment by dosvath** [comment]
Hi @SanchayGupta1197, thank you for this effort! Since we started some ITs earlier, could you rebase these changes on top of this branch https://github.com/confluentinc/kafka-connect-storage-cloud/pull/351 and update the PR?

**Comment by SanchayGupta1197** [comment]
HI @dosvath, there are two branches `confluentinc:5.5.x` and your's `initial-ITs2`. Could you please confirm which of the branches to rebase my PR on?

**Comment by dosvath** [comment]
> HI @dosvath, there are two branches `confluentinc:5.5.x` and your's `initial-ITs2`. Could you please confirm which of the branches to rebase my PR on?

You can use `dosvath:Initial-ITs2`, thank you :)

**Comment by SanchayGupta1197** [comment]
Rebased the changes on top of #351 and raised a new PR #373 against `5.5.x`. Closing this PR.  
Updated the [Jira Ticket](https://confluentinc.atlassian.net/browse/HCD-329) with the new PR

**Pull request closed without merging**
