### PR TITLE
Implement Azure Blob Storage sink connector

### PR DESCRIPTION
**Pull request by rolanddb**
Added AZ Blob Sink as discussed in #124

### CODE REVIEW

**Comment by rolanddb** [comment]
Can someone help out here: the Jenkins build is failing for some reason, but I cannot access the 'details' link (https://jenkins.confluent.io/job/confluentinc-pr/job/kafka-connect-storage-cloud/job/PR-129/1/display/redirect) because it times out. So I have no way to investigate the cause of the failure!

**Comment by kkonstantine** [comment]
Thanks for the PR @rolanddb! 

Before we begin the reviews, allow me to suggest the following: 

- Rebase your changes on top of master
- Please remove any licenses and notices. They add too much noise and they are not required for merging (only for release). 
- Feel free to check https://github.com/confluentinc/kafka-connect-storage-cloud/pull/128 for how a similar work has started for Google Cloud Storage (GCS)
- Let's call this module `kafka-connect-azure` since there's no standard acronym for `Azure Blob Storage`

To answer a previous question of yours, we don't publish an Intellij code style for connectors at the moment, but Google systel should be close https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml and should help with several checkstyle errors.

**Comment by rolanddb** [comment]
@kkonstantine thanks for the pointers.

I've rebased onto master, removed the licenses & notices, and renamed the module to kafka-connect-azure.

Similar refactorings as in #128 still need to be made - so I guess this PR remains WIP in that regard.

I did some attempt, but I lack sufficient knowledge about the intended structure of the connector. It looks like `format.avro.AvroFormat` could be in common, but `format.avro.AvroRecordWriterProvider` is specific to s3/gcs/azure since it implements specific write/commit logic, correct?

The `TopicPartitionWriter` has a dependency on `RecordWriterProvider<AzBlobSinkConnectorConfig>`. I think this should be refactored to `RecordWriterProvider<? extends StorageSinkConnectorConfig>`. Though I am not sure if the `RecordWriterProvider` really need to be typed - can't we just use an interface that implements `RecordWriter getRecordWriter(StorageSinkConnectorConfig, String commitFilename)`?

**Comment by cricket007** [comment]
You might want to try rebasing again. Your PR should start at 5e2808a

**Comment by rolanddb** [comment]
I pushed the branch again, hoping the PR would be cleaner/easier to review (without all the licence files etc). This has unfortunately closed the PR which was not my intention. Shall I create a new PR or can you reopen it? Sorry for the trouble!

**Comment by cricket007** [comment]
Looks like you deleted your remote branch.

**Comment by kkonstantine** [comment]
@rolanddb Not sure why the branch was deleted when you forced push your changes. 

Feel free to open a new PR, making sure it contains only your commits with your desired changes.

**Comment by rolanddb** [comment]
@kkonstantine Thanks, and sorry for the noise. Please see #130.

**Pull request closed without merging**
