### PR TITLE
s3.send.digest option, default false

### PR DESCRIPTION
**Pull request by mark-mckelvy**
## Problem
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/760, https://github.com/confluentinc/kafka-connect-storage-cloud/issues/710: S3 Object Locking requires an MD5 digest to be sent with the multipart upload request, otherwise it will be rejected.

## Solution
Include new option, `s3.send.digest`, that when set to `true` will include MD5 digest with upload parts.

##### Does this solution apply anywhere else?
- [ ] yes
- [X] no

##### Testing done:
- [X] Unit tests
- [ ] Integration tests
- [ ] System tests
- [X] Manual tests

## Release Plan

 
Merge to master.

Developed in conjunction with @paul-dellinger

### CODE REVIEW

**Comment by mark-mckelvy** [comment]
> [CLA assistant check](https://cla-assistant.io/confluentinc/kafka-connect-storage-cloud?pullRequest=757) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/confluentinc/kafka-connect-storage-cloud?pullRequest=757) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/confluentinc/kafka-connect-storage-cloud?pullRequest=757) it.

I've authorized CLA Assistant on my account and see this:

image

**Comment by mark-mckelvy** [comment]
> > [CLA assistant check](https://cla-assistant.io/confluentinc/kafka-connect-storage-cloud?pullRequest=757) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/confluentinc/kafka-connect-storage-cloud?pullRequest=757) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/confluentinc/kafka-connect-storage-cloud?pullRequest=757) it.
> 
> I've authorized CLA Assistant on my account and see this:
> 
> image
> 
> @kkonstantine or @patrick-premont can you advise?
> 
> Other repositories don't seem to have this issue. For example:
> 
> * https://cla-assistant.io/gchq/CyberChef
> * https://cla-assistant.io/FerretDB/FerretDB

Looks like it is working now.

**Review by subhashiyer9 — COMMENTED** [review]
Thanks for the changes @mark-mckelvy.
I have few minor comments. Rest looks good.

One other comment.. Is it possible to add some integration test to verify the md5 digest we are sending is matching what s3 expects?

**Comment by mark-mckelvy** [comment]
> Thanks for the changes @mark-mckelvy. I have few minor comments. Rest looks good.
> 
> One other comment.. Is it possible to add some integration test to verify the md5 digest we are sending is matching what s3 expects?

@subhashiyer9: Thank you for the review! 052f04da570e5ab6292b7ec977909614e465c1d5 contains the changes you requested. Please let me know if there's anything else.

**Comment by subhashiyer9** [comment]
> > Thanks for the changes @mark-mckelvy. I have few minor comments. Rest looks good.
> > One other comment.. Is it possible to add some integration test to verify the md5 digest we are sending is matching what s3 expects?
> 
> @subhashiyer9: Thank you for the review! [052f04d](https://github.com/confluentinc/kafka-connect-storage-cloud/commit/052f04da570e5ab6292b7ec977909614e465c1d5) contains the changes you requested. Please let me know if there's anything else.

Can you update the base branch to 10.5.x or any of the older branches?
Otherwise, the changes looks good to me.

**Comment by subhashiyer9** [comment]
> @subhashiyer9: I've rebased on 10.5.x. Should the target still be master?
Can you also change the target to 10.5.x?

**Comment by mark-mckelvy** [comment]
> > @subhashiyer9: I've rebased on 10.5.x. Should the target still be master?
> 
> Can you also change the target to 10.5.x?

No problem, retargeted!

**Comment by mark-mckelvy** [comment]
Ready for merge

**Pull request merged**
